# Configuracionn de la base de datos
spring.datasource.url=jdbc:postgresql://dpg-d3tnclre5dus73949mig-a.oregon-postgres.render.com:5432/solicitud_k436
# spring.datasource.url=jdbc:postgresql://localhost:5432/solicitudes
spring.datasource.username=admin
spring.datasource.password=SmGzbAVAuCIFyanyN0PvNUe2MOEwe1tf
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracionn de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator (monitoreo)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Devtools (reinicio automatico en desarrollo)
spring.devtools.restart.enabled=true