# Configuracionn de la base de datos
spring.datasource.url=jdbc:postgresql://dpg-d4u7u263jp1c73cha20g-a.oregon-postgres.render.com:5432/solicitud_mo8d
# spring.datasource.url=jdbc:postgresql://localhost:5432/solicitudes
spring.datasource.username=admin
spring.datasource.password=TBP2U21WJ19jvl7XgrHw47oUOCiGRTRh
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracionn de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator (monitoreo)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Devtools (reinicio automatico en desarrollo)
spring.devtools.restart.enabled=true